version: '3'

services:
  pppwn:
    build:
      context: .
      dockerfile: Dockerfile.pppwn
    container_name: pppwn
    network_mode: "host"
    environment:
      - INTERFACE=enx74dadaf4bd40
      - FIRMWAREVERSION=1100
    cap_add:
    - NET_ADMIN
    - NET_RAW
    privileged: true
    volumes:
      - ./pppwn:/docker_pppwn/pppwn
      - ./pppwn/web/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./pppwn/web/supervisor/supervisord.conf:/etc/supervisord.conf
      - ./pppwn/web/app/public:/var/www/html
    restart: unless-stopped
